// templates/go-inertia-vue-shell/resources/js/Pages/Contact.vue
<template>
  <Layout :title="title">
    <div class="container max-w-4xl mx-auto">
      <div class="rounded-xl border bg-card text-card-foreground shadow">
        <div class="flex flex-col space-y-1.5 p-6">
          <div class="font-semibold leading-none tracking-tight text-3xl">{{ title }}</div>
        </div>
        <div class="p-6 pt-0 space-y-6">
          <form @submit.prevent="submit" class="space-y-4">
            <div class="space-y-2">
              <label for="name" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">Name:</label>
              <Input
                id="name"
                v-model="form.name"
                type="text"
                required
              />
            </div>
            <div class="space-y-2">
              <label for="email" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">Email:</label>
              <Input
                id="email"
                v-model="form.email"
                type="email"
                required
              />
            </div>
            <div class="space-y-2">
              <label for="message" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">Message:</label>
              <Textarea
                id="message"
                v-model="form.message"
                rows="5"
                required
              />
            </div>
            <div class="flex gap-4">
              <Button type="submit" :disabled="form.processing">
                {{ form.processing ? 'Sending...' : 'Send Message' }}
              </Button>
              <Button variant="outline" as="a" href="/">Back to Home</Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3';
import Layout from '../Components/Layout.vue';
import Button from '../components/ui/button.vue';
import Input from '../components/ui/input.vue';
import Textarea from '../components/ui/textarea.vue';

defineProps({
  title: String,
});

const form = useForm({
  name: '',
  email: '',
  message: '',
});

function submit() {
  form.post('/contact');
}
</script>

// templates/go-inertia-react-shell/resources/js/Pages/Contact.jsx
import React, { useState } from 'react';
import { useForm, Link } from '@inertiajs/react';
import Layout from '../Components/Layout';

export default function Contact({ title }) {
  const { data, setData, post, processing } = useForm({
    name: '',
    email: '',
    message: '',
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    post('/contact');
  };

  return (
    <Layout title={title}>
      <div className="container">
        <h1>{title}</h1>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Name:</label>
            <input
              type="text"
              id="name"
              value={data.name}
              onChange={e => setData('name', e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="email">Email:</label>
            <input
              type="email"
              id="email"
              value={data.email}
              onChange={e => setData('email', e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="message">Message:</label>
            <textarea
              id="message"
              value={data.message}
              onChange={e => setData('message', e.target.value)}
              rows="5"
              required
            />
          </div>
          <button type="submit" disabled={processing}>
            {processing ? 'Sending...' : 'Send Message'}
          </button>
        </form>
        <Link href="/" className="back-link">Back to Home</Link>
      </div>
    </Layout>
  );
}
