// templates/go-inertia-react-shell/resources/js/Pages/About.jsx
import React from 'react';
import { Link } from '@inertiajs/react';
import Layout from '../Components/Layout';

export default function About({ title, content }) {
  return (
    <Layout title={title}>
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-8">
        <h1 className="text-4xl font-bold text-slate-800 mb-6">{title}</h1>
        <p className="text-lg text-gray-600 mb-8">{content}</p>
        <Link 
          href="/" 
          className="inline-block px-6 py-3 bg-slate-600 text-white font-medium rounded-lg hover:bg-slate-700 transition-colors"
        >
          Back to Home
        </Link>
      </div>
    </Layout>
  );
}

// templates/go-inertia-vue-shell/resources/js/Pages/About.vue
<template>
  <Layout :title="title">
    <div class="container max-w-4xl mx-auto">
      <div class="rounded-xl border bg-card text-card-foreground shadow">
        <div class="flex flex-col space-y-1.5 p-6">
          <div class="font-semibold leading-none tracking-tight text-3xl">{{ title }}</div>
        </div>
        <div class="p-6 pt-0 space-y-4">
          <p class="text-muted-foreground">{{ content }}</p>
          <Button variant="outline" as="a" href="/">Back to Home</Button>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script setup>
import { Link } from '@inertiajs/vue3';
import Layout from '../Components/Layout.vue';
import Button from '../components/ui/button.vue';

defineProps({
  title: String,
  content: String,
});
</script>
